class SeatsList {
  static final List<List<String>> seats = [
    [
      'available',
      'available',
      'unavailable',
      'available',
      'available',
      'unavailable'
    ],
    [
      'available',
      'available',
      'unavailable',
      'available',
      'available',
      'unavailable'
    ],
    [
      'available',
      'available',
      'unavailable',
      'available',
      'available',
      'unavailable'
    ],
    [
      'unavailable',
      'unavailable',
      'unavailable',
      'available',
      'available',
      'unavailable'
    ],
    [
      'available',
      'available',
      'available',
      'available',
      'available',
      'available'
    ],
    [
      'available',
      'available',
      'unavailable',
      'unavailable',
      'unavailable',
      'unavailable'
    ],
    [
      'available',
      'available',
      'available',
      'available',
      'available',
      'available'
    ],
    [
      'available',
      'available',
      'unavailable',
      'available',
      'available',
      'unavailable'
    ],
  ];
}
